### PR TITLE
Optimization/sort

### PR DESCRIPTION
**Pull request by FedorShcherbakov**
- Added "npm start" script to run dev server and grunt in watch mode
- Reduced code repetition
- Handled browser's prev/next page events
- Fixed Safari checkbox selection bug
- Optimised jQuery selectors
- Added node_modules to .gitignore

### CODE REVIEW

**Review by dcerimagic — CHANGES_REQUESTED** [review]
Found a bug when compared to master which will need to be ironed out.

Broken tabs: after you've clicked the search button (magnifying glass in the header) you're taken to results-search.html page. Notice when on master there's only one tab selected with loading animation running, while on optimization/sort branch you have all of these opened and clicking between tabs doesn't work anymore. Tabs on /search-tabbed.html page are also broken so we can conclude this is a site-wide problem. Note that tabs on the search-tabbed page can also be navigated via tab key so that functionality needs to remain intact.

**Comment by FedorShcherbakov** [comment]
@dcerimagic updated

**Comment by dcerimagic** [comment]
@eqApe close, but if you look at /results-search.html on master branch, you'll see that the first tab's spinner is not activated by default and that the spinner will only show after you've clicked its tab.

**Comment by immigrantsheep** [comment]
Dude :) provjeri da li me možeš maknuti

**Comment by FedorShcherbakov** [comment]
@dcerimagic thanks, fixed

**Review by dcerimagic — APPROVED** [review]

**Pull request merged**
